Repository appuio/component-openshift4-monitoring, pull requests merged in 2022-03, with the labels that each got.

#82 Add resource management alerts
  class/defaults.yml
  component/capacity.libsonnet
  component/main.jsonnet
  docs/modules/ROOT/pages/explanations/resource_management.adoc
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/pages/runbooks/cpucapacity.adoc
  docs/modules/ROOT/pages/runbooks/memorycapacity.adoc
  docs/modules/ROOT/pages/runbooks/podcapacity.adoc
  docs/modules/ROOT/pages/runbooks/resourcerequests.adoc
  docs/modules/ROOT/partials/nav.adoc
Labels: enhancement

#85 Add option to multiply the default thresholds for capacity alerts
  class/defaults.yml
  component/capacity.libsonnet
Labels: enhancement

#86 Handle non integer factors for capacity alerts
  component/capacity.libsonnet
Labels: bug

#88 Update modulesync config
  .sync.yml
Labels: ignore

#89 Add definitions and test for release 4.10
  .sync.yml
  class/defaults.yml
  class/openshift4-monitoring.yml
  tests/release-4.10.yml
Labels: dependency

#90 Enable golden tests
  .sync.yml
Labels: ignore
