Repository appuio/component-openshift4-monitoring, pull requests merged in 2022-11, with the labels that each got.

#132 Explicitly configure projected SA token volume for silence cronjob
  component/silence.jsonnet
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/silence.yaml
Labels: bug

#133 Enable user workload monitoring by default
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/user-workload-monitoring.yml
Labels: enhancement

#134 Aggregate `monitoring.coreos.com` objects to `cluster-reader`
  component/aggregated-clusterroles.libsonnet
  component/main.jsonnet
  docs/modules/ROOT/pages/index.adoc
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
Labels: enhancement

#137 Adjust HighOverallControlPlaneMemory alert on OCP4.11
  class/defaults.yml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
Labels: change

#136 Provide component library with functions for alert patching and filtering
  class/defaults.yml
  component/rules.jsonnet
  docs/modules/ROOT/partials/nav.adoc
  lib/openshift4-monitoring-alert-patching.libsonnet
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
Labels: enhancement

#138 Actually add documentation page for alertpatching lib
  docs/modules/ROOT/pages/references/alert-patching.adoc
Labels: ignore

#139 Fix patch for HighOverallControlPlaneMemory alert rule
  class/defaults.yml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
Labels: bug
