Repository appuio/component-openshift4-monitoring, pull requests merged in 2022-05, with the labels that each got.

#78 Update dependency quay.io/appuio/oc to v4.9
  class/defaults.yml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/silence.yaml
Labels: dependency

#102 Pull changes from upstream to golden tests
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
Labels: ignore

#103 Remove configurable threshold from defaults.yml
  class/defaults.yml
  component/capacity.libsonnet
  docs/modules/ROOT/pages/runbooks/cpucapacity.adoc
  docs/modules/ROOT/pages/runbooks/memorycapacity.adoc
  docs/modules/ROOT/pages/runbooks/podcapacity.adoc
  docs/modules/ROOT/pages/runbooks/resourcerequests.adoc
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
Labels: breaking

#104 Fix typo
  class/defaults.yml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
Labels: ignore

#105 Give prometheus permissions to auto-discover targets
  component/main.jsonnet
  component/rbac.libsonnet
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/rbac.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/rbac.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/rbac.yaml
Labels: bug
