Repository appuio/component-openshift4-monitoring, pull requests merged in 2023-05, with the labels that each got.

#149 Add support for grouping capacity alerts by node label
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/defaults.yml
  component/capacity.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/capacity-alerts-with-node-labels.yml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/apps/openshift4-monitoring.yaml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/01_secrets.yaml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/90_syn_monitoring.yaml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/rbac.yaml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
Labels: enhancement

#150 Download and render vsphere-problem-detector alertrules
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/openshift4-monitoring.yml
  component/rules.jsonnet
  tests/golden/vsphere/openshift4-monitoring/apps/openshift4-monitoring.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/01_secrets.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/90_syn_monitoring.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/rbac.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/vsphere.yml
Labels: enhancement

#151 Remove support for component-prometheus (syn-monitoring)
  class/defaults.yml
  component/main.jsonnet
  component/syn-monitoring.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/capacity-alerts-with-node-labels.yml
  tests/capacity-alerts.yml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/90_syn_monitoring.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/90_syn_monitoring.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/90_syn_monitoring.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/90_syn_monitoring.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/90_syn_monitoring.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/90_syn_monitoring.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/90_syn_monitoring.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/90_syn_monitoring.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/90_syn_monitoring.yaml
  tests/release-4.10.yml
  tests/release-4.11.yml
  tests/release-4.9.yml
  tests/remote-write.yml
  tests/user-workload-monitoring.yml
  tests/vsphere.yml
Labels: breaking

#152 Use `patch-operator.libsonnet` directly
  component/main.jsonnet
  tests/capacity-alerts-with-node-labels.yml
  tests/capacity-alerts.yml
  tests/es-operator-rules.yml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/release-4.10.yml
  tests/release-4.11.yml
  tests/release-4.9.yml
  tests/remote-write.yml
  tests/user-workload-monitoring.yml
  tests/vsphere.yml
Labels: change

#153 Allow remoteWrite for user workload monitoring to be configured in hierarchy
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/01_secrets.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/remote-write.yml
Labels: enhancement

#155 Inject `syn_team` label for all alerts
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  component/capacity.libsonnet
  lib/openshift4-monitoring-alert-patching.libsonnet
  tests/golden/team-label/openshift4-monitoring/apps/openshift4-monitoring.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/01_secrets.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/rbac.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/team-label.yml
Labels: enhancement
