Repository appuio/component-openshift4-monitoring, pull requests merged in 2023-07, with the labels that each got.

#143 Remove Elasticsearch operator alerts
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/defaults.yml
  class/openshift4-monitoring.yml
  component/rules.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/es-operator-rules.yml
  tests/golden/es-operator-rules/openshift4-monitoring/apps/openshift4-monitoring.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/01_secrets.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/rbac.yaml
  tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/silence.yaml
Labels: breaking

#164 Remove parameter `upstreamRules.clusterSamplesOperator`
  class/defaults.yml
  component/rules.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: breaking

#166 Drop support for OpenShift 4.9 and 4.10
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/defaults.yml
  class/openshift4-monitoring.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/capacity-alerts-with-node-labels.yml
  tests/capacity-alerts.yml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.10/openshift4-monitoring/apps/openshift4-monitoring.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/01_secrets.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/rbac.yaml
  tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/release-4.9/openshift4-monitoring/apps/openshift4-monitoring.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/01_secrets.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/rbac.yaml
  tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/release-4.10.yml
  tests/release-4.9.yml
Labels: breaking

#168 Switch remaining non-release-specific test cases to OCP 4.13
  tests/custom-rules.yml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/user-workload-monitoring.yml
  tests/vsphere.yml
Labels: change

#169 Add 1min time overlap for silence cronjob
  component/scripts/silence.sh
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/silence.yaml
Labels: change

#171 Respect existing `syn_team` labels when patching alerts
  lib/openshift4-monitoring-alert-patching.libsonnet
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/custom_rules.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/team-label.yml
Labels: enhancement

#172 Correctly handle alerts with no labels
  lib/openshift4-monitoring-alert-patching.libsonnet
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/custom_rules.yaml
  tests/team-label.yml
Labels: bug
