Repository appuio/component-openshift4-monitoring, pull requests merged in 2023-08, with the labels that each got.

#173 Add cluster and tenant names to external labels
  class/defaults.yml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
Labels: enhancement

#174 Block gossip traffic between alertmanagers in different namespaces
  class/defaults.yml
  component/main.jsonnet
  component/networkpolicy.libsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
Labels: bug

#175 Add `cluster_id` external label for UWM Prometheus
  class/defaults.yml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
Labels: change

#176 Allow using alert patching library in post process filters
  lib/openshift4-monitoring-alert-patching.libsonnet
Labels: enhancement
