Repository appuio/component-openshift4-monitoring, pull requests merged in 2023-10, with the labels that each got.

#181 Automatic alert mapping from application (instance) to team
  .cruft.json
  .github/workflows/test.yaml
  Makefile.vars.mk
  class/defaults.yml
  component/alert-routing-discovery.libsonnet
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  lib/openshift4-monitoring-alert-patching.libsonnet
  lib/openshift4-monitoring-prom.libsonnet
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/team-routing/openshift4-monitoring/apps/openshift4-monitoring.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/01_secrets.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/99_discovery_debug_cm.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/custom_rules.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/rbac.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/team-label.yml
  tests/team-routing.yml
Labels: enhancement

#183 Allow removing instances from `syn.teams`
  lib/openshift4-monitoring-prom.libsonnet
  tests/team-routing.yml
Labels: bug

#184 Make alert routing discovery output easier to review
  component/alert-routing-discovery.libsonnet
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/99_discovery_debug_cm.yaml
  tests/team-routing.yml
Labels: enhancement

#185 Fix formatting in component docs
  docs/modules/ROOT/pages/references/parameters.adoc
  docs/modules/ROOT/pages/references/prom.adoc
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
Labels: documentation

#187 Replace dead link to Alertmanager config reference
  docs/modules/ROOT/pages/references/parameters.adoc
Labels: bug

#188 Allow setting remote write default parameters
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
  tests/remote-write.yml
Labels: enhancement
