Repository appuio/component-openshift4-monitoring, pull requests merged in 2024-11, with the labels that each got.

#217 Make hidden `runbook_url` annotations visible
  component/rules.jsonnet
Labels: bug, bump:patch

#215 Update quay.io/appuio/oc Docker tag to v4.16
  class/defaults.yml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/cronjobs.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/release-4.15/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/release-4.16/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/silence.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/silence.yaml
Labels: dependency, bump:patch

#220 Enable `PodDisruptionBudgetAtLimit` alert to find maintenance blocking PDBs
  class/defaults.yml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.15/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.16/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
Labels: enhancement, bump:patch
