Repository appuio/component-openshift4-monitoring, pull requests merged in 2024-08, with the labels that each got.

#211 Fix alertmanager-allow-web networkpolicy
  component/networkpolicy.libsonnet
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.15/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/release-4.15/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
Labels: bug, bump:patch

#213 Add alert for high TCP memory utilization on nodes
  component/rules.jsonnet
  docs/modules/ROOT/pages/runbooks/tcp-memory-usage.adoc
  docs/modules/ROOT/partials/nav.adoc
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.15/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
Labels: enhancement

#206 Update quay.io/prometheus/node-exporter Docker tag to v1.8.2
  class/defaults.yml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/appuio_node_exporter.yaml
Labels: dependency, automerge, bump:patch

#214 Update quay.io/brancz/kube-rbac-proxy Docker tag to v0.18.1
  class/defaults.yml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/appuio_node_exporter.yaml
  tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.15/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
Labels: dependency, automerge, bump:patch
