Repository appuio/component-openshift4-monitoring, pull requests merged in 2024-12, with the labels that each got.

#222 Add config section `metricsServer`
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.15/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.16/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
Labels: enhancement, bump:minor

#221 Update quay.io/brancz/kube-rbac-proxy Docker tag to v0.18.2
  class/defaults.yml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/appuio_node_exporter.yaml
Labels: dependency, automerge, bump:patch

#218 Update dependency https://github.com/kubernetes/kube-state-metrics to v2.14.0
  class/defaults.yml
Labels: dependency

#223 Allow traffic from cluster nodes to all workloads in the monitoring namespace
  component/networkpolicy.libsonnet
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.15/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.16/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/user-workload-monitoring.yml
Labels: bug, bump:patch

#224 Use `syn-teams.libsonnet` for alert routing discovery and alert patching
  component/alert-routing-discovery.libsonnet
  jsonnetfile.jsonnet
  lib/openshift4-monitoring-alert-patching.libsonnet
  lib/openshift4-monitoring-prom.libsonnet
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/99_discovery_debug_cm.yaml
  tests/team-routing.yml
Labels: change, bump:minor
