Repository appuio/component-openshift4-monitoring, pull requests merged in 2025-02, with the labels that each got.

#231 Update quay.io/brancz/kube-rbac-proxy Docker tag to v0.19.0
  class/defaults.yml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/appuio_node_exporter.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.16/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/release-4.17/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
Labels: dependency, bump:minor, automerge

#230 Update quay.io/prometheus/node-exporter Docker tag to v1.9.0
  class/defaults.yml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/appuio_node_exporter.yaml
Labels: dependency, bump:minor, automerge

#232 Update fields of `cluster-monitoring-config` for OpenShift 4.16 and newer
  class/defaults.yml
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.16/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.17/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
Labels: enhancement, bump:minor

#234 Don't apply default config for `cluster-monitoring-config` fields which don't support `nodeSelector`
  class/defaults.yml
  component/main.jsonnet
  docs/modules/ROOT/pages/references/parameters.adoc
  tests/custom-rules.yml
  tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.16/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/release-4.17/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
  tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
Labels: bug, bump:patch
